"""empty message

Revision ID: 0397713b36f0
Revises: None
Create Date: 2016-07-26 11:32:42.141600

"""

# revision identifiers, used by Alembic.
revision = '0397713b36f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=150), nullable=True),
    sa.Column('channel', sa.String(length=150), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id')
    )
    op.drop_table('apps')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('integration_id', sa.VARCHAR(length=40), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=150), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=150), nullable=True),
    sa.Column('developer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], [u'developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id')
    )
    op.drop_table('integrations')
    ### end Alembic commands ###
