"""empty message

Revision ID: 331e122ac51f
Revises: 8a49d733d502
Create Date: 2016-10-11 17:30:01.316623

"""

# revision identifiers, used by Alembic.
revision = '331e122ac51f'
down_revision = '8a49d733d502'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('githubs', sa.Column('hook_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('githubs', 'hook_id')
    ### end Alembic commands ###
