"""empty message

Revision ID: 4ec9c1890d4e
Revises: None
Create Date: 2017-01-20 11:44:06.163370

"""

# revision identifiers, used by Alembic.
revision = '4ec9c1890d4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_key', sa.String(length=40), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_id', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('avatar', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id')
    )
    op.create_index(op.f('ix_developers_dev_key'), 'developers', ['dev_key'], unique=True)
    op.create_index(op.f('ix_developers_username'), 'developers', ['username'], unique=False)
    op.create_table('authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_token', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=150), nullable=True),
    sa.Column('token', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id')
    )
    op.create_table('githubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('repository', sa.String(length=150), nullable=True),
    sa.Column('hook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('githubs')
    op.drop_table('integrations')
    op.drop_table('channels')
    op.drop_table('authorizations')
    op.drop_index(op.f('ix_developers_username'), table_name='developers')
    op.drop_index(op.f('ix_developers_dev_key'), table_name='developers')
    op.drop_table('developers')
    ### end Alembic commands ###
