"""empty message

Revision ID: 94182c7bc5a3
Revises: eb4f45fc11c1
Create Date: 2016-10-31 13:48:20.485435

"""

# revision identifiers, used by Alembic.
revision = '94182c7bc5a3'
down_revision = 'eb4f45fc11c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('owner', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'owner')
    ### end Alembic commands ###
