"""empty message

Revision ID: 961b4faca01c
Revises: None
Create Date: 2016-08-15 13:33:19.753006

"""

# revision identifiers, used by Alembic.
revision = '961b4faca01c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('token', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'token')
    ### end Alembic commands ###
