"""empty message

Revision ID: 9b92ed8d4d8d
Revises: 331e122ac51f
Create Date: 2016-10-28 10:51:17.271827

"""

# revision identifiers, used by Alembic.
revision = '9b92ed8d4d8d'
down_revision = '331e122ac51f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_token', sa.String(length=150), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorizations')
    ### end Alembic commands ###
