"""empty message

Revision ID: ba2804042b42
Revises: ecd129ed1a57
Create Date: 2016-10-10 10:12:31.845408

"""

# revision identifiers, used by Alembic.
revision = 'ba2804042b42'
down_revision = 'ecd129ed1a57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'type')
    ### end Alembic commands ###
