"""empty message

Revision ID: ecd129ed1a57
Revises: None
Create Date: 2016-08-29 11:09:25.760323

"""

# revision identifiers, used by Alembic.
revision = 'ecd129ed1a57'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('avatar', sa.String(length=150), nullable=True))
    op.add_column('developers', sa.Column('description', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'description')
    op.drop_column('developers', 'avatar')
    ### end Alembic commands ###
